//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RTEvents.com.megaokul.gateway {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HERYONESMSWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class HERYONESMSWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MAYATEK_SMS_SENDEROperationCompleted;
        
        private System.Threading.SendOrPostCallback SMS_ILETI_SORGULAOperationCompleted;
        
        private System.Threading.SendOrPostCallback SMS_ALFANUMERIK_BASLIK_SORGULAOperationCompleted;
        
        private System.Threading.SendOrPostCallback SMS_KREDI_SORGULAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HERYONESMSWebService() {
            this.Url = global::RTEvents.Properties.Settings.Default.OKUL_com_megaokul_gateway_HERYONESMSWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MAYATEK_SMS_SENDERCompletedEventHandler MAYATEK_SMS_SENDERCompleted;
        
        /// <remarks/>
        public event SMS_ILETI_SORGULACompletedEventHandler SMS_ILETI_SORGULACompleted;
        
        /// <remarks/>
        public event SMS_ALFANUMERIK_BASLIK_SORGULACompletedEventHandler SMS_ALFANUMERIK_BASLIK_SORGULACompleted;
        
        /// <remarks/>
        public event SMS_KREDI_SORGULACompletedEventHandler SMS_KREDI_SORGULACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MAYATEK_SMS_SENDER", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MAYATEK_SMS_SENDER(string KULLANICI, string SIFRE, string ORGINATOR, int MESAJ_DILI, string GSMNO, string MESAJ, int TAKIPNO) {
            object[] results = this.Invoke("MAYATEK_SMS_SENDER", new object[] {
                        KULLANICI,
                        SIFRE,
                        ORGINATOR,
                        MESAJ_DILI,
                        GSMNO,
                        MESAJ,
                        TAKIPNO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MAYATEK_SMS_SENDERAsync(string KULLANICI, string SIFRE, string ORGINATOR, int MESAJ_DILI, string GSMNO, string MESAJ, int TAKIPNO) {
            this.MAYATEK_SMS_SENDERAsync(KULLANICI, SIFRE, ORGINATOR, MESAJ_DILI, GSMNO, MESAJ, TAKIPNO, null);
        }
        
        /// <remarks/>
        public void MAYATEK_SMS_SENDERAsync(string KULLANICI, string SIFRE, string ORGINATOR, int MESAJ_DILI, string GSMNO, string MESAJ, int TAKIPNO, object userState) {
            if ((this.MAYATEK_SMS_SENDEROperationCompleted == null)) {
                this.MAYATEK_SMS_SENDEROperationCompleted = new System.Threading.SendOrPostCallback(this.OnMAYATEK_SMS_SENDEROperationCompleted);
            }
            this.InvokeAsync("MAYATEK_SMS_SENDER", new object[] {
                        KULLANICI,
                        SIFRE,
                        ORGINATOR,
                        MESAJ_DILI,
                        GSMNO,
                        MESAJ,
                        TAKIPNO}, this.MAYATEK_SMS_SENDEROperationCompleted, userState);
        }
        
        private void OnMAYATEK_SMS_SENDEROperationCompleted(object arg) {
            if ((this.MAYATEK_SMS_SENDERCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MAYATEK_SMS_SENDERCompleted(this, new MAYATEK_SMS_SENDERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SMS_ILETI_SORGULA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SMS_ILETI_SORGULA(string MESAJ_ID, string KULLANICI, string SIFRE) {
            object[] results = this.Invoke("SMS_ILETI_SORGULA", new object[] {
                        MESAJ_ID,
                        KULLANICI,
                        SIFRE});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SMS_ILETI_SORGULAAsync(string MESAJ_ID, string KULLANICI, string SIFRE) {
            this.SMS_ILETI_SORGULAAsync(MESAJ_ID, KULLANICI, SIFRE, null);
        }
        
        /// <remarks/>
        public void SMS_ILETI_SORGULAAsync(string MESAJ_ID, string KULLANICI, string SIFRE, object userState) {
            if ((this.SMS_ILETI_SORGULAOperationCompleted == null)) {
                this.SMS_ILETI_SORGULAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSMS_ILETI_SORGULAOperationCompleted);
            }
            this.InvokeAsync("SMS_ILETI_SORGULA", new object[] {
                        MESAJ_ID,
                        KULLANICI,
                        SIFRE}, this.SMS_ILETI_SORGULAOperationCompleted, userState);
        }
        
        private void OnSMS_ILETI_SORGULAOperationCompleted(object arg) {
            if ((this.SMS_ILETI_SORGULACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SMS_ILETI_SORGULACompleted(this, new SMS_ILETI_SORGULACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SMS_ALFANUMERIK_BASLIK_SORGULA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet SMS_ALFANUMERIK_BASLIK_SORGULA(string KULLANICI, string SIFRE) {
            object[] results = this.Invoke("SMS_ALFANUMERIK_BASLIK_SORGULA", new object[] {
                        KULLANICI,
                        SIFRE});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void SMS_ALFANUMERIK_BASLIK_SORGULAAsync(string KULLANICI, string SIFRE) {
            this.SMS_ALFANUMERIK_BASLIK_SORGULAAsync(KULLANICI, SIFRE, null);
        }
        
        /// <remarks/>
        public void SMS_ALFANUMERIK_BASLIK_SORGULAAsync(string KULLANICI, string SIFRE, object userState) {
            if ((this.SMS_ALFANUMERIK_BASLIK_SORGULAOperationCompleted == null)) {
                this.SMS_ALFANUMERIK_BASLIK_SORGULAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSMS_ALFANUMERIK_BASLIK_SORGULAOperationCompleted);
            }
            this.InvokeAsync("SMS_ALFANUMERIK_BASLIK_SORGULA", new object[] {
                        KULLANICI,
                        SIFRE}, this.SMS_ALFANUMERIK_BASLIK_SORGULAOperationCompleted, userState);
        }
        
        private void OnSMS_ALFANUMERIK_BASLIK_SORGULAOperationCompleted(object arg) {
            if ((this.SMS_ALFANUMERIK_BASLIK_SORGULACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SMS_ALFANUMERIK_BASLIK_SORGULACompleted(this, new SMS_ALFANUMERIK_BASLIK_SORGULACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SMS_KREDI_SORGULA", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SMS_KREDI_SORGULA(string KULLANICI, string SIFRE) {
            object[] results = this.Invoke("SMS_KREDI_SORGULA", new object[] {
                        KULLANICI,
                        SIFRE});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SMS_KREDI_SORGULAAsync(string KULLANICI, string SIFRE) {
            this.SMS_KREDI_SORGULAAsync(KULLANICI, SIFRE, null);
        }
        
        /// <remarks/>
        public void SMS_KREDI_SORGULAAsync(string KULLANICI, string SIFRE, object userState) {
            if ((this.SMS_KREDI_SORGULAOperationCompleted == null)) {
                this.SMS_KREDI_SORGULAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSMS_KREDI_SORGULAOperationCompleted);
            }
            this.InvokeAsync("SMS_KREDI_SORGULA", new object[] {
                        KULLANICI,
                        SIFRE}, this.SMS_KREDI_SORGULAOperationCompleted, userState);
        }
        
        private void OnSMS_KREDI_SORGULAOperationCompleted(object arg) {
            if ((this.SMS_KREDI_SORGULACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SMS_KREDI_SORGULACompleted(this, new SMS_KREDI_SORGULACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void MAYATEK_SMS_SENDERCompletedEventHandler(object sender, MAYATEK_SMS_SENDERCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MAYATEK_SMS_SENDERCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MAYATEK_SMS_SENDERCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SMS_ILETI_SORGULACompletedEventHandler(object sender, SMS_ILETI_SORGULACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SMS_ILETI_SORGULACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SMS_ILETI_SORGULACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SMS_ALFANUMERIK_BASLIK_SORGULACompletedEventHandler(object sender, SMS_ALFANUMERIK_BASLIK_SORGULACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SMS_ALFANUMERIK_BASLIK_SORGULACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SMS_ALFANUMERIK_BASLIK_SORGULACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SMS_KREDI_SORGULACompletedEventHandler(object sender, SMS_KREDI_SORGULACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SMS_KREDI_SORGULACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SMS_KREDI_SORGULACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591